"""Reader Python SDK."""

from .async_client import AsyncReaderClient
from .client import ReaderClient
from .errors import (
    ConcurrencyLimitedError,
    ConflictError,
    InsufficientCreditsError,
    InternalServerError,
    InvalidRequestError,
    NotFoundError,
    RateLimitedError,
    ReaderApiError,
    ReaderError,
    ScrapeTimeoutError,
    UnauthenticatedError,
    UpstreamUnavailableError,
    UrlBlockedError,
    to_reader_api_error,
)
from .types import (
    CreditInfo,
    Credits,
    DoneEvent,
    ErrorEvent,
    Job,
    JobInfo,
    JobReadResult,
    Page,
    PageEvent,
    Pagination,
    ProgressEvent,
    ReadParams,
    ReadResult,
    ScrapeMetadata,
    ScrapeReadResult,
    ScrapeResult,
    StreamEvent,
    UsageEntry,
    WebhookConfig,
)

__all__ = [
    "ReaderClient",
    "AsyncReaderClient",
    # Errors
    "ReaderApiError",
    "ReaderError",
    "InvalidRequestError",
    "UnauthenticatedError",
    "InsufficientCreditsError",
    "UrlBlockedError",
    "NotFoundError",
    "ConflictError",
    "RateLimitedError",
    "ConcurrencyLimitedError",
    "InternalServerError",
    "UpstreamUnavailableError",
    "ScrapeTimeoutError",
    "to_reader_api_error",
    # Types
    "ReadParams",
    "ReadResult",
    "ScrapeReadResult",
    "JobReadResult",
    "ScrapeResult",
    "ScrapeMetadata",
    "Page",
    "Job",
    "JobInfo",
    "Credits",
    "CreditInfo",
    "Pagination",
    "UsageEntry",
    # Stream events
    "StreamEvent",
    "ProgressEvent",
    "PageEvent",
    "ErrorEvent",
    "DoneEvent",
    "WebhookConfig",
]
